
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  broker: your mosquitto address
  port: your mosquitto port
  username: your mosquitto auth id
  password: your mosquitto auth password

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: warning

light:
  - platform: mqtt
    name: "거실 천장 1"
    unique_id: "livingroomlight1"
    schema: template
    state_topic: "home/hillstate/light/state/1/1"
    command_topic: "home/hillstate/light/command/1/1"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "거실 천장 2"
    unique_id: "livingroomlight2"
    schema: template
    state_topic: "home/hillstate/light/state/1/2"
    command_topic: "home/hillstate/light/command/1/2"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "복도 천장"
    unique_id: "hallwaylight"
    schema: template
    state_topic: "home/hillstate/light/state/1/3"
    command_topic: "home/hillstate/light/command/1/3"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "침실 천장"
    unique_id: "bedroomlight"
    schema: template
    state_topic: "home/hillstate/light/state/2/1"
    command_topic: "home/hillstate/light/command/2/1"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "실외기실 천장"
    unique_id: "outdoorunitlight"
    schema: template
    state_topic: "home/hillstate/light/state/2/2"
    command_topic: "home/hillstate/light/command/2/2"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "서재 천장"
    unique_id: "librarylight"
    schema: template
    state_topic: "home/hillstate/light/state/3/1"
    command_topic: "home/hillstate/light/command/3/1"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "컴퓨터방 천장"
    unique_id: "pcroomlight"
    schema: template
    state_topic: "home/hillstate/light/state/4/1"
    command_topic: "home/hillstate/light/command/4/1"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "식탁 천장"
    unique_id: "tablelight"
    schema: template
    state_topic: "home/hillstate/light/state/6/1"
    command_topic: "home/hillstate/light/command/6/1"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false
  - platform: mqtt
    name: "조리대 천장"
    unique_id: "countertoplight"
    schema: template
    state_topic: "home/hillstate/light/state/6/2"
    command_topic: "home/hillstate/light/command/6/2"
    state_template: "{% if value_json.state %} on {% else %} off {% endif %}"
    command_on_template: '{"state": 1}'
    command_off_template: '{"state": 0}'
    optimistic: false

switch:
  - platform: mqtt
    name: "거실 콘센트 1"
    unique_id: "livingroom_outlet_1"
    state_topic: "home/hillstate/outlet/state/1/1"
    command_topic: "home/hillstate/outlet/command/1/1"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "거실 콘센트 2"
    unique_id: "livingroom_outlet_2"
    state_topic: "home/hillstate/outlet/state/1/2"
    command_topic: "home/hillstate/outlet/command/1/2"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "침실 콘센트 1"
    unique_id: "bedroom_outlet_1"
    state_topic: "home/hillstate/outlet/state/2/1"
    command_topic: "home/hillstate/outlet/command/2/1"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "침실 콘센트 2"
    unique_id: "bedroom_outlet_2"
    state_topic: "home/hillstate/outlet/state/2/2"
    command_topic: "home/hillstate/outlet/command/2/2"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "서재 콘센트 1"
    unique_id: "library_outlet_1"
    state_topic: "home/hillstate/outlet/state/3/1"
    command_topic: "home/hillstate/outlet/command/3/1"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "서재 콘센트 2"
    unique_id: "library_outlet_2"
    state_topic: "home/hillstate/outlet/state/3/2"
    command_topic: "home/hillstate/outlet/command/3/2"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "컴퓨터방 콘센트 1"
    unique_id: "pcroom_outlet_1"
    state_topic: "home/hillstate/outlet/state/4/1"
    command_topic: "home/hillstate/outlet/command/4/1"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "컴퓨터방 콘센트 2"
    unique_id: "pcroom_outlet_2"
    state_topic: "home/hillstate/outlet/state/4/2"
    command_topic: "home/hillstate/outlet/command/4/2"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "주방 콘센트 1"
    unique_id: "kitchen_outlet_1"
    state_topic: "home/hillstate/outlet/state/6/1"
    command_topic: "home/hillstate/outlet/command/6/1"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "주방 콘센트 2"
    unique_id: "kitchen_outlet_2"
    state_topic: "home/hillstate/outlet/state/6/2"
    command_topic: "home/hillstate/outlet/command/6/2"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:power-socket-de
  - platform: mqtt
    name: "가스 밸브"
    unique_id: "kitchengasvalve"
    state_topic: "home/hillstate/gasvalve/state"
    command_topic: "home/hillstate/gasvalve/command"
    value_template: '{ "state": {{ value_json.state }} }'
    payload_on: '{ "state": 1 }'
    payload_off: '{ "state": 0 }'
    retain: false
    icon: mdi:pipe-valve

http:
  ssl_certificate: ssl/fullchain.pem
  ssl_key: ssl/privkey.pem

google_assistant:
  project_id: your google assistant project id
  service_account: !include gcp_service_account.json
  report_state: true
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - sensor
    - fan
    - button
    - climate
    - binary sensor